# Generated by Django 3.1.5 on 2022-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=64)),
                ('room', models.IntegerField()),
                ('product', models.CharField(max_length=64)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
